insert into public.stores (
  id,
  owner_id,
  name,
  area,
  has_daytime,
  has_night,
  opening_hour_day,
  opening_hour_night,
  pr_structure,
  strong_days,
  strong_events,
  weak_events,
  trust_seed
) values
  ('retreat-bar', null, 'RETREAT BAR', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('arabesque', null, 'ARABESQUE', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('agreeable', null, 'AgreeAble', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('colors-bar', null, 'COLORS BAR', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('bar440', null, 'BAR440', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('voluptuous', null, 'Voluptuous', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('club-scarlet-tokyo', null, 'CLUB SCARLET TOKYO', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('honey-trap', null, 'HONEY TRAP', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('bar-rusk', null, 'BAR RUSK', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('papillon', null, 'Papillon', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('harnes-tokyo', null, 'HARNES TOKYO', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('bar-face', null, 'BAR FACE', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('campo-bar', null, 'CAMPO BAR', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('bar-spear', null, 'BAR SPEAR', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('bar-canelo', null, 'BAR CANELO', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('mille-feuille', null, 'Mille-feuille', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('filt-shibuya', null, 'FILT SHIBUYA', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('b-dash', null, 'B-DASH', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('ogikubo-himitsu-club', null, '荻窪秘密倶楽部', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('club-zeus', null, 'CLUB ZEUS', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('land-land', null, 'land land', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('collabo', null, 'collabo', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('neo', null, 'Neo', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('communicationbar-sango', null, 'Communicationbar 珊瑚', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60),
  ('secret-bar-silent-moon', null, 'Secret Bar Silent Moon', '未設定', false, true, '', '19:00', '未分類', array[]::text[], array[]::text[], array[]::text[], 60)
on conflict (id) do update set
  owner_id = excluded.owner_id,
  name = excluded.name,
  area = excluded.area,
  has_daytime = excluded.has_daytime,
  has_night = excluded.has_night,
  opening_hour_day = excluded.opening_hour_day,
  opening_hour_night = excluded.opening_hour_night,
  pr_structure = excluded.pr_structure,
  strong_days = excluded.strong_days,
  strong_events = excluded.strong_events,
  weak_events = excluded.weak_events,
  trust_seed = excluded.trust_seed,
  updated_at = now();

insert into public.bbs_sources (
  id,
  store_id,
  label,
  url,
  parser_type,
  active,
  crawl_interval_minutes,
  last_status
) values
  ('retreat-bar-bbs', 'retreat-bar', 'BBS', 'https://retreatbar.jp/bbs/', 'auto', true, 5, 'pending'),
  ('arabesque-bbs', 'arabesque', 'BBS', 'https://arabesque.jpn.com/topics/', 'auto', true, 5, 'pending'),
  ('agreeable-bbs', 'agreeable', 'BBS', 'https://agreeable.bar/topics/', 'auto', true, 5, 'pending'),
  ('colors-bar-bbs', 'colors-bar', 'BBS', 'https://t-colors.net/message', 'auto', true, 5, 'pending'),
  ('bar440-bbs', 'bar440', 'BBS', 'https://rara.jp/bar440/', 'auto', true, 5, 'pending'),
  ('voluptuous-bbs', 'voluptuous', 'BBS', 'https://voluptuous.tokyo/bbs', 'auto', true, 5, 'pending'),
  ('club-scarlet-tokyo-bbs', 'club-scarlet-tokyo', 'BBS', 'https://scarlet.tokyo/', 'auto', true, 5, 'pending'),
  ('honey-trap-bbs', 'honey-trap', 'BBS', 'https://bar-honeytrap.com/bbs/', 'auto', true, 5, 'pending'),
  ('bar-rusk-bbs', 'bar-rusk', 'BBS', 'https://bar-rusk.com/bbs/', 'auto', true, 5, 'pending'),
  ('papillon-bbs', 'papillon', 'BBS', 'https://bar-papillon.net/message', 'auto', true, 5, 'pending'),
  ('harnes-tokyo-bbs', 'harnes-tokyo', 'BBS', 'https://harnes.tokyo/event-calendar/', 'auto', true, 5, 'pending'),
  ('bar-face-bbs', 'bar-face', 'BBS', 'https://bar-face.jp/bbs/', 'auto', true, 5, 'pending'),
  ('campo-bar-bbs', 'campo-bar', 'BBS', 'https://campo-bar.com/bbs/', 'auto', true, 5, 'pending'),
  ('bar-spear-bbs', 'bar-spear', 'BBS', 'https://www.barspear.com/bbs/', 'auto', true, 5, 'pending'),
  ('bar-canelo-bbs', 'bar-canelo', 'BBS', 'https://barcanelo.com/bbs/', 'auto', true, 5, 'pending'),
  ('mille-feuille-bbs', 'mille-feuille', 'BBS', 'https://millefeuillesby.apage.jp/', 'auto', true, 5, 'pending'),
  ('filt-shibuya-bbs', 'filt-shibuya', 'BBS', 'https://filtshibuya.com/bbs/', 'auto', true, 5, 'pending'),
  ('b-dash-bbs', 'b-dash', 'BBS', 'https://b-dash.bar/topics/', 'auto', true, 5, 'pending'),
  ('ogikubo-himitsu-club-bbs', 'ogikubo-himitsu-club', 'BBS', 'https://ogikubo0620.com/forums/forum/bbs/', 'auto', true, 5, 'pending'),
  ('club-zeus-bbs', 'club-zeus', 'BBS', 'https://rara.jp/zeus/', 'auto', true, 5, 'pending'),
  ('land-land-bbs', 'land-land', 'BBS', 'https://land2021.com/bbs2/', 'auto', true, 5, 'pending'),
  ('collabo-bbs', 'collabo', 'BBS', 'https://m.z-z.jp/?collabo123', 'auto', true, 5, 'pending'),
  ('neo-bbs', 'neo', 'BBS', 'https://neo-bbs.com/', 'auto', true, 5, 'pending'),
  ('communicationbar-sango-bbs', 'communicationbar-sango', 'BBS', 'https://bar-sango.com/bbs/', 'auto', true, 5, 'pending'),
  ('silent-moon-bbs', 'secret-bar-silent-moon', 'BBS', 'https://www.silent-moon.net/jp/silentmoon-bbs.php', 'auto', true, 5, 'pending')
on conflict (store_id, url) do update set
  label = excluded.label,
  parser_type = excluded.parser_type,
  active = excluded.active,
  crawl_interval_minutes = excluded.crawl_interval_minutes,
  last_status = excluded.last_status,
  updated_at = now();
