create table if not exists public.store_daily_rollups (
  store_id text not null references public.stores(id) on delete cascade,
  date_key date not null,
  post_count integer not null default 0,
  unique_author_count integer not null default 0,
  female_post_count integer not null default 0,
  male_post_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (store_id, date_key)
);

alter table public.bbs_sources alter column crawl_interval_minutes set default 5;
update public.bbs_sources set crawl_interval_minutes = 5 where active = true and crawl_interval_minutes <> 5;

create table if not exists public.store_hourly_rollups (
  store_id text not null references public.stores(id) on delete cascade,
  hour_start timestamptz not null,
  snapshot_count integer not null default 0,
  average_radar_score numeric(6,2),
  crawl_count integer not null default 0,
  successful_crawl_count integer not null default 0,
  blocked_crawl_count integer not null default 0,
  failed_crawl_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (store_id, hour_start)
);

create table if not exists public.operational_alerts (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  severity text not null default 'error' check (severity in ('warning', 'error')),
  details jsonb not null default '{}'::jsonb,
  delivery_status text not null default 'pending' check (delivery_status in ('pending', 'sent', 'failed', 'unconfigured')),
  created_at timestamptz not null default now()
);

create index if not exists operational_alerts_created_idx on public.operational_alerts (created_at desc);
create index if not exists store_daily_rollups_date_idx on public.store_daily_rollups (date_key desc);
create index if not exists store_hourly_rollups_hour_idx on public.store_hourly_rollups (hour_start desc);

alter table public.store_daily_rollups enable row level security;
alter table public.store_hourly_rollups enable row level security;
alter table public.operational_alerts enable row level security;

create or replace function public.run_night_radar_retention(
  snapshot_retention_days integer default 14,
  crawl_retention_days integer default 30,
  normalized_post_retention_days integer default 90
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_snapshots integer := 0;
  deleted_crawls integer := 0;
  deleted_posts integer := 0;
begin
  insert into public.store_daily_rollups (
    store_id, date_key, post_count, unique_author_count, female_post_count, male_post_count, updated_at
  )
  select
    store_id,
    (coalesce(posted_at, observed_at) at time zone 'Asia/Tokyo')::date,
    count(*)::integer,
    count(distinct nullif(lower(trim(author_name)), '記載なし'))::integer,
    count(*) filter (where author_gender in ('女性', '女', '単女', '単独女性', '♀'))::integer,
    count(*) filter (where author_gender in ('男性', '男', '単男', '単独男性', '♂'))::integer,
    now()
  from public.bbs_normalized_posts
  group by store_id, (coalesce(posted_at, observed_at) at time zone 'Asia/Tokyo')::date
  on conflict (store_id, date_key) do update set
    post_count = excluded.post_count,
    unique_author_count = excluded.unique_author_count,
    female_post_count = excluded.female_post_count,
    male_post_count = excluded.male_post_count,
    updated_at = now();

  insert into public.store_hourly_rollups (
    store_id, hour_start, snapshot_count, average_radar_score, updated_at
  )
  select store_id, date_trunc('hour', captured_at), count(*)::integer, avg(radar_score), now()
  from public.bbs_snapshots
  group by store_id, date_trunc('hour', captured_at)
  on conflict (store_id, hour_start) do update set
    snapshot_count = excluded.snapshot_count,
    average_radar_score = excluded.average_radar_score,
    updated_at = now();

  insert into public.store_hourly_rollups (
    store_id, hour_start, crawl_count, successful_crawl_count, blocked_crawl_count, failed_crawl_count, updated_at
  )
  select
    store_id,
    date_trunc('hour', fetched_at),
    count(*)::integer,
    count(*) filter (where status = 'ok')::integer,
    count(*) filter (where status = 'blocked')::integer,
    count(*) filter (where status = 'failed')::integer,
    now()
  from public.crawl_runs
  group by store_id, date_trunc('hour', fetched_at)
  on conflict (store_id, hour_start) do update set
    crawl_count = excluded.crawl_count,
    successful_crawl_count = excluded.successful_crawl_count,
    blocked_crawl_count = excluded.blocked_crawl_count,
    failed_crawl_count = excluded.failed_crawl_count,
    updated_at = now();

  delete from public.bbs_snapshots
  where captured_at < now() - make_interval(days => greatest(7, snapshot_retention_days));
  get diagnostics deleted_snapshots = row_count;

  delete from public.crawl_runs
  where fetched_at < now() - make_interval(days => greatest(14, crawl_retention_days));
  get diagnostics deleted_crawls = row_count;

  delete from public.bbs_normalized_posts
  where observed_at < now() - make_interval(days => greatest(30, normalized_post_retention_days));
  get diagnostics deleted_posts = row_count;

  delete from public.operational_alerts where created_at < now() - interval '90 days';

  return jsonb_build_object(
    'deletedSnapshots', deleted_snapshots,
    'deletedCrawlRuns', deleted_crawls,
    'deletedNormalizedPosts', deleted_posts,
    'completedAt', now()
  );
end;
$$;

revoke all on function public.run_night_radar_retention(integer, integer, integer) from public;
grant execute on function public.run_night_radar_retention(integer, integer, integer) to service_role;
